// Compiles a task's description + comment/update history into a clean
// Markdown document — the "auto documenter" feature. Pure function so it can
// be reused by the task detail page (single-task export) and the /docs page
// (whole-project export).

function fmtDate(d) {
  if (!d) return "—";
  try {
    return new Date(d).toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return d;
  }
}

export function generateTaskDoc(task, comments, allTasks) {
  const thread = comments
    .filter((c) => c.ticketId === task.id)
    .sort((a, b) => (a.created < b.created ? -1 : 1));

  const subtasks = allTasks.filter((t) => t.parentId === task.id);
  const parent = task.parentId
    ? allTasks.find((t) => t.id === task.parentId)
    : null;

  const lines = [];
  lines.push(`# ${task.name}`);
  lines.push("");
  lines.push(
    `**Ticket:** ${task.ticketId}  |  **Type:** ${task.type}  |  **Status:** ${task.status}  |  **Priority:** ${task.priority}`
  );
  lines.push(
    `**Assignee:** ${task.assignee}  |  **Start:** ${fmtDate(
      task.startDate
    )}  |  **Target:** ${fmtDate(task.targetDate)}  |  **Progress:** ${
      task.progress || 0
    }%`
  );
  if (parent) {
    lines.push(`**Parent task:** ${parent.ticketId} — ${parent.name}`);
  }
  if (task.jiraLink) lines.push(`**Jira:** ${task.jiraLink}`);
  if (task.githubBranch && task.githubBranch !== "N/A") {
    lines.push(`**Branch:** \`${task.githubBranch}\``);
  }
  lines.push(`**Source:** ${task.syncSource} | **Last update:** ${fmtDate(task.lastUpdate)}`);
  lines.push("");
  lines.push("## Description");
  lines.push("");
  lines.push(task.description?.trim() || "_No description provided._");
  lines.push("");

  if (subtasks.length > 0) {
    lines.push("## Subtasks");
    lines.push("");
    for (const s of subtasks) {
      lines.push(`- [${s.status}] **${s.ticketId}** — ${s.name} (${s.assignee})`);
    }
    lines.push("");
  }

  lines.push("## Update history");
  lines.push("");
  if (thread.length === 0) {
    lines.push("_No updates logged yet._");
  } else {
    for (const c of thread) {
      lines.push(`- **${fmtDate(c.created)}** · ${c.author}: ${c.text}`);
    }
  }
  lines.push("");
  lines.push("---");
  lines.push(`_Generated by Taskar on ${fmtDate(new Date().toISOString())}_`);

  return lines.join("\n");
}

export function generateProjectDoc(tasks, comments) {
  const topLevel = tasks.filter((t) => !t.parentId);
  const lines = [];
  lines.push("# Project Documentation");
  lines.push("");
  lines.push(
    `_Auto-generated from ${tasks.length} tasks and ${comments.length} logged updates on ${fmtDate(
      new Date().toISOString()
    )}._`
  );
  lines.push("");
  lines.push("## Table of contents");
  lines.push("");
  for (const t of topLevel) {
    lines.push(`- [${t.ticketId} — ${t.name}](#${slug(t.name)})`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const t of topLevel) {
    lines.push(generateTaskDoc(t, comments, tasks));
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

function slug(s) {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-");
}

// Byte-order mark: what makes Word read the payload as UTF-8 rather than the
// system codepage, which otherwise mangles anything non-ASCII.
const UTF8_BOM = "﻿";

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function downloadMarkdown(filename, content) {
  downloadBlob(filename, new Blob([content], { type: "text/markdown;charset=utf-8" }));
}

// Word, Pages and Google Docs all open an HTML payload served as .doc. The
export function downloadWordDoc(filename, html) {
  downloadBlob(
    filename,
    new Blob([UTF8_BOM, html], { type: "application/msword;charset=utf-8" })
  );
}
