// Compiles a note (freeform or MOM) into a clean Markdown document — the
// "auto documenter" feature for Notes, mirroring docGenerator.js's approach
// for tasks. Pure functions so they're reusable by both the note editor
// (single-note export) and the /notes list page (compile-all export).

import { toMarkdown, toHtml, escapeHtml } from "./richText.js";

// A note's body is a rich document; notes written before the rich editor
// only have plain text. Both export, so every reader goes through here.
function bodyMarkdown(note) {
  if (note.bodyRich) return toMarkdown(note.bodyRich).trim();
  return (note.body || "").trim();
}

function bodyHtml(note) {
  if (note.bodyRich) return toHtml(note.bodyRich);
  return (note.body || "")
    .split(/\r?\n/)
    .map((line) => "<p>" + escapeHtml(line) + "</p>")
    .join("");
}

function fmtDate(d) {
  if (!d) return "—";
  try {
    return new Date(d).toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return d;
  }
}

export function generateNoteDoc(note, tasks) {
  const linkedTask = note.linkedTaskId
    ? tasks.find((t) => t.id === note.linkedTaskId)
    : null;

  const lines = [];
  lines.push(`# ${note.title || "Untitled note"}`);
  lines.push("");

  const meta = [`**Type:** ${note.type === "mom" ? "Minutes of Meeting" : "Freeform"}`];
  meta.push(`**Date:** ${fmtDate(note.createdAt)}`);
  if (linkedTask) {
    meta.push(`**Linked task:** ${linkedTask.ticketId} — ${linkedTask.name}`);
  }
  lines.push(meta.join("  |  "));
  lines.push("");

  if (note.type === "mom") {
    lines.push("## Attendees");
    lines.push("");
    if (note.attendees.length === 0) {
      lines.push("_No attendees recorded._");
    } else {
      for (const a of note.attendees) lines.push(`- ${a}`);
    }
    lines.push("");

    lines.push("## Agenda");
    lines.push("");
    if (note.agenda.length === 0) {
      lines.push("_No agenda recorded._");
    } else {
      for (const a of note.agenda) lines.push(`- ${a}`);
    }
    lines.push("");

    lines.push("## Discussion");
    lines.push("");
    lines.push(bodyMarkdown(note) || "_No discussion notes._");
    lines.push("");

    lines.push("## Action Items");
    lines.push("");
    if (note.actionItems.length === 0) {
      lines.push("_No action items._");
    } else {
      for (const item of note.actionItems) {
        const box = item.done ? "[x]" : "[ ]";
        let link = "";
        if (item.taskId) {
          const t = tasks.find((x) => x.id === item.taskId);
          link = t ? ` → ${t.ticketId}` : "";
        }
        lines.push(`- ${box} ${item.text}${link}`);
      }
    }
  } else {
    lines.push("## Note");
    lines.push("");
    lines.push(bodyMarkdown(note) || "_No content._");
  }

  lines.push("");
  lines.push("---");
  lines.push(`_Generated by Taskar on ${fmtDate(new Date().toISOString())}_`);

  return lines.join("\n");
}

export function generateNotesCompilationDoc(notes, tasks) {
  const lines = [];
  lines.push("# Notes");
  lines.push("");
  lines.push(
    `_Auto-generated from ${notes.length} note${notes.length === 1 ? "" : "s"} on ${fmtDate(
      new Date().toISOString()
    )}._`
  );
  lines.push("");
  lines.push("## Table of contents");
  lines.push("");
  for (const n of notes) {
    lines.push(`- [${n.title || "Untitled note"}](#${slug(n.title || "untitled-note")})`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const n of notes) {
    lines.push(generateNoteDoc(n, tasks));
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

function slug(s) {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-");
}

// ---------------------------------------------------------------------------
// Word export
// ---------------------------------------------------------------------------

// A .doc that Word, Pages and Google Docs all open natively: HTML carrying the
// Office namespaces. Unlike the Markdown export above this keeps colour, font
// size, alignment and tables, none of which Markdown can express.
function section(heading, html) {
  return `<h2 style="font-size: 13pt; margin: 18pt 0 6pt">${heading}</h2>${html}`;
}

function listHtml(items) {
  if (!items || items.length === 0) return "<p><em>None recorded.</em></p>";
  return `<ul>${items.map((i) => `<li>${escapeHtml(i)}</li>`).join("")}</ul>`;
}

export function generateNoteWordHtml(note, tasks) {
  const linkedTask = note.linkedTaskId
    ? tasks.find((t) => t.id === note.linkedTaskId)
    : null;
  const title = escapeHtml(note.title || "Untitled note");

  const meta = [
    `Type: ${note.type === "mom" ? "Minutes of Meeting" : "Freeform"}`,
    `Date: ${fmtDate(note.createdAt)}`,
  ];
  if (linkedTask) meta.push(`Linked task: ${linkedTask.ticketId} — ${linkedTask.name}`);

  const parts = [
    `<h1 style="font-size: 18pt; margin: 0 0 4pt">${title}</h1>`,
    `<p style="color: #64748b; font-size: 9pt; margin: 0 0 18pt">${escapeHtml(
      meta.join("  |  ")
    )}</p>`,
  ];

  if (note.type === "mom") {
    parts.push(section("Attendees", listHtml(note.attendees)));
    parts.push(section("Agenda", listHtml(note.agenda)));
    parts.push(
      section("Discussion", bodyHtml(note) || "<p><em>No discussion notes.</em></p>")
    );
    const items = note.actionItems || [];
    parts.push(
      section(
        "Action items",
        items.length === 0
          ? "<p><em>No action items.</em></p>"
          : `<ul style="list-style: none; padding-left: 1em">${items
              .map((item) => {
                const t = item.taskId ? tasks.find((x) => x.id === item.taskId) : null;
                const suffix = t ? ` → ${escapeHtml(t.ticketId)}` : "";
                return `<li>${item.done ? "☑" : "☐"} ${escapeHtml(item.text)}${suffix}</li>`;
              })
              .join("")}</ul>`
      )
    );
  } else {
    parts.push(bodyHtml(note) || "<p><em>No content.</em></p>");
  }

  return [
    '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">',
    "<head>",
    '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />',
    `<title>${title}</title>`,
    "<style>body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; color: #0f172a; }</style>",
    "</head>",
    `<body>${parts.join("")}</body>`,
    "</html>",
  ].join("");
}
