// Compiles a note (freeform or MOM) into a clean Markdown document — the
// "auto documenter" feature for Notes, mirroring docGenerator.js's approach
// for tasks. Pure functions so they're reusable by both the note editor
// (single-note export) and the /notes list page (compile-all export).

function fmtDate(d) {
  if (!d) return "—";
  try {
    return new Date(d).toLocaleDateString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return d;
  }
}

export function generateNoteDoc(note, tasks) {
  const linkedTask = note.linkedTaskId
    ? tasks.find((t) => t.id === note.linkedTaskId)
    : null;

  const lines = [];
  lines.push(`# ${note.title || "Untitled note"}`);
  lines.push("");

  const meta = [`**Type:** ${note.type === "mom" ? "Minutes of Meeting" : "Freeform"}`];
  meta.push(`**Date:** ${fmtDate(note.createdAt)}`);
  if (linkedTask) {
    meta.push(`**Linked task:** ${linkedTask.ticketId} — ${linkedTask.name}`);
  }
  lines.push(meta.join("  |  "));
  lines.push("");

  if (note.type === "mom") {
    lines.push("## Attendees");
    lines.push("");
    if (note.attendees.length === 0) {
      lines.push("_No attendees recorded._");
    } else {
      for (const a of note.attendees) lines.push(`- ${a}`);
    }
    lines.push("");

    lines.push("## Agenda");
    lines.push("");
    if (note.agenda.length === 0) {
      lines.push("_No agenda recorded._");
    } else {
      for (const a of note.agenda) lines.push(`- ${a}`);
    }
    lines.push("");

    lines.push("## Discussion");
    lines.push("");
    lines.push(note.body?.trim() || "_No discussion notes._");
    lines.push("");

    lines.push("## Action Items");
    lines.push("");
    if (note.actionItems.length === 0) {
      lines.push("_No action items._");
    } else {
      for (const item of note.actionItems) {
        const box = item.done ? "[x]" : "[ ]";
        let link = "";
        if (item.taskId) {
          const t = tasks.find((x) => x.id === item.taskId);
          link = t ? ` → ${t.ticketId}` : "";
        }
        lines.push(`- ${box} ${item.text}${link}`);
      }
    }
  } else {
    lines.push("## Note");
    lines.push("");
    lines.push(note.body?.trim() || "_No content._");
  }

  lines.push("");
  lines.push("---");
  lines.push(`_Generated by Taskar on ${fmtDate(new Date().toISOString())}_`);

  return lines.join("\n");
}

export function generateNotesCompilationDoc(notes, tasks) {
  const lines = [];
  lines.push("# Notes");
  lines.push("");
  lines.push(
    `_Auto-generated from ${notes.length} note${notes.length === 1 ? "" : "s"} on ${fmtDate(
      new Date().toISOString()
    )}._`
  );
  lines.push("");
  lines.push("## Table of contents");
  lines.push("");
  for (const n of notes) {
    lines.push(`- [${n.title || "Untitled note"}](#${slug(n.title || "untitled-note")})`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const n of notes) {
    lines.push(generateNoteDoc(n, tasks));
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

function slug(s) {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-");
}
