import manifest from "@/data/guideManifest.json";
import PageHeader from "@/components/PageHeader";

export const metadata = { title: "User Guide — Taskar" };

export default function GuidePage() {
  return (
    <div className="flex-1">
      <PageHeader
        title="User Guide"
        subtitle={
          <>
            Auto-generated by walking the live app with a headless browser
            and capturing each screen — run{" "}
            <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs">
              npm run guide
            </code>{" "}
            any time the UI changes to refresh these screenshots. A Markdown
            copy is also written to{" "}
            <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs">
              USER_GUIDE.md
            </code>{" "}
            in the project root.
          </>
        }
      />

      <div className="px-4 py-6 sm:px-8">
        {manifest.length === 0 ? (
          <div className="max-w-xl rounded-xl border border-dashed border-slate-300 bg-white p-6 text-sm text-slate-500">
            No screenshots yet. Start the dev server and run{" "}
            <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs">
              npm run guide
            </code>{" "}
            to generate this guide.
          </div>
        ) : (
          <div className="space-y-10">
            {manifest.map((step, i) => (
              <section key={step.file} className="max-w-3xl">
                <div className="mb-3 flex items-baseline gap-2">
                  <span className="text-xs font-semibold text-slate-300">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <h2 className="text-base font-semibold text-slate-900">
                    {step.title}
                  </h2>
                </div>
                <p className="mb-3 text-sm leading-relaxed text-slate-600">
                  {step.description}
                </p>
                <div className="overflow-hidden rounded-xl border border-slate-200 shadow-sm">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={step.file}
                    alt={step.title}
                    className="w-full"
                    loading="lazy"
                  />
                </div>
              </section>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
